"""refactor: replace avatar_url with avatar_file_id and has_avatar

Revision ID: 2dcb9dec9879
Revises: 5f663632a5e8
Create Date: 2025-11-16 21:45:12.082852

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2dcb9dec9879"
down_revision = "5f663632a5e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(
            sa.Column("avatar_file_id", sa.String(length=36), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "has_avatar", sa.Boolean(), nullable=False, server_default="0"
            )
        )

        # Remove avatar_url column (replaced by avatar_file_id)
        batch_op.drop_column("avatar_url")

    # Backfill has_avatar based on existing data
    # Note: avatar_file_id will remain NULL until users re-upload their avatars
    # or a separate migration script extracts file_id from Storage Service
    op.execute(
        "UPDATE user SET has_avatar = 0 WHERE avatar_file_id IS NULL OR avatar_file_id = ''"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        # Restore avatar_url column
        batch_op.add_column(
            sa.Column("avatar_url", sa.VARCHAR(length=255), nullable=True)
        )

        # Drop new columns
        batch_op.drop_column("has_avatar")
        batch_op.drop_column("avatar_file_id")
    # ### end Alembic commands ###
