"""Increase avatar_url field size to 1024 characters

Revision ID: 3950c1dd0418
Revises: deec18879e97
Create Date: 2025-11-08 17:40:08.273052

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3950c1dd0418"
down_revision = "deec18879e97"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "avatar_url",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=1024),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "avatar_url",
            existing_type=sa.String(length=1024),
            type_=sa.VARCHAR(length=255),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
