"""feat: add logo_file_id and has_logo to Company model

Revision ID: 94eff3b51102
Revises: 2dcb9dec9879
Create Date: 2025-11-16 22:16:20.563165

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "94eff3b51102"
down_revision = "2dcb9dec9879"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company", schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(
            sa.Column("logo_file_id", sa.String(length=36), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "has_logo", sa.Boolean(), nullable=False, server_default="0"
            )
        )

        # Remove logo_url column (replaced by logo_file_id)
        batch_op.drop_column("logo_url")

    # Backfill has_logo based on existing data
    # Note: logo_file_id will remain NULL until companies re-upload their logos
    op.execute(
        "UPDATE company SET has_logo = 0 WHERE logo_file_id IS NULL OR logo_file_id = ''"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company", schema=None) as batch_op:
        # Restore logo_url column
        batch_op.add_column(
            sa.Column("logo_url", sa.VARCHAR(length=255), nullable=True)
        )

        # Drop new columns
        batch_op.drop_column("has_logo")
        batch_op.drop_column("logo_file_id")
    # ### end Alembic commands ###
