"""Add password reset fields to user table (Issue #12 Phase 1)

Revision ID: 9748d4f19f62
Revises: e74fe3a3a1bd
Create Date: 2025-11-22 03:57:02.292951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9748d4f19f62'
down_revision = 'e74fe3a3a1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_required', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_password_change', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_password_change')
        batch_op.drop_column('password_reset_required')

    # ### end Alembic commands ###
