"""Make user company_id nullable for superusers

Revision ID: eb530714b64e
Revises: 
Create Date: 2025-07-27 16:00:26.155762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb530714b64e'
down_revision = '5bb308cd0183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Make company_id nullable for superuser creation
    op.alter_column('user', 'company_id',
                    existing_type=sa.String(length=36),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert company_id to not nullable
    op.alter_column('user', 'company_id',
                    existing_type=sa.String(length=36),
                    nullable=False)
    # ### end Alembic commands ###
